# Generated by Django 3.2.6 on 2024-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='hireDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phoneNumber',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truckNumber',
            field=models.IntegerField(),
        ),
    ]
